add ignore_plugins and to_me config
XZhouQD/nonebot-plugin-help pull request #6
Opened 2023-06-12 09:21 UTC by renmu123

支持`ignore_plugins`配置，可配置不希望help插件列出的插件包名列表，例如，以下配置可忽略`nonebot_plugin_localstore`与`nonebot_plugin_apscheduler`插件。  
支持`to_me`配置，可配置是否只有私聊或者艾特时才响应help命令。

```
ignore_plugins=["nonebot_plugin_localstore", "nonebot_plugin_apscheduler"]
to_me=true
```

2023-06-13 17:52 UTC, XZhouQD commented
Hi @renmu123 , thank you for PR, please have a look at review comments. If you do not have time to make those change, I can do the change after this PR merged, just reply to me and I can complete that part.

2023-06-14 00:59 UTC, XZhouQD requested changes

2023-06-14 00:59 UTC, XZhouQD commented on nonebot_plugin_help/config.py
> +    ignore_plugins: Optional[list] = []
better to use help_ignore_plugins as config parameter - use help as parameter keyword to avoid possible conflict with other plugins. do not forget to change readme and handler as well.

2023-06-14 00:59 UTC, XZhouQD commented on nonebot_plugin_help/config.py
> +    to_me: Optional[bool] = False
ditto

2023-06-14 00:59 UTC, XZhouQD commented on nonebot_plugin_help/handler.py
> +            if plugin.name in plugin_config.ignore_plugins:
Consider another situation - if user use /help <plugin_name> where <plugin_name> is in `ignored_plugins` but user typed it directly? Should the plugin help be outputed normally through the else clause (through L63) of this condition statement or should it also be hidden, controlled by ignore_plugins? This also applies to plugin nickname or helpname.

2023-06-14 00:59 UTC, XZhouQD commented on README.md
> +支持`ignore_plugins`配置，可配置不希望help插件列出的插件包名列表，例如，以下配置可忽略`nonebot_plugin_localstore`与`nonebot_plugin_apscheduler`插件。
Try follow the priority and block part and make the ignore_plugins & to_me part as a separate section - put a badge there as well would be preferred - the badge indicates the feature supported version. You may leave the version empty there and I can change that later - although it would be 0.6.0.

2023-06-15 02:08 UTC, renmu123 commented
Thanks for your review, l will change it this week

2023-06-19 06:24 UTC, renmu123 commented on nonebot_plugin_help/handler.py
> +            if plugin.name in plugin_config.ignore_plugins:
I think `help_ignore_plugins` should not be applied to `help <plugin_name>`. The robot owner may use a single plugin for the help command, and these commands should need to be hidden from end users. Even if end users learn about the hidden plugin certain sensitive commands, it doesn't matter as there are permission controls for sensitive operations. 
It all depends on you.

2023-06-19 06:51 UTC, XZhouQD approved these changes
Generally looks good, some minor changes on readme can be left to me later. If you have no further changes, just reply here so I can complete the merge.

2023-06-19 06:51 UTC, XZhouQD commented on nonebot_plugin_help/config.py
> +    ignore_plugins: Optional[list] = []
Done, L2

2023-06-19 06:51 UTC, XZhouQD commented on nonebot_plugin_help/config.py
> +    to_me: Optional[bool] = False
Done, L2

2023-06-19 06:52 UTC, XZhouQD commented on README.md
> +支持`ignore_plugins`配置，可配置不希望help插件列出的插件包名列表，例如，以下配置可忽略`nonebot_plugin_localstore`与`nonebot_plugin_apscheduler`插件。
Some further minor changes can be left to me later, will mark this as resolved. L3

2023-06-19 06:53 UTC, XZhouQD commented on nonebot_plugin_help/handler.py
> +            if plugin.name in plugin_config.ignore_plugins:
Sounds good, let's keep it as is.

2023-06-19 07:04 UTC, renmu123 commented
> Generally looks good, some minor changes on readme can be left to me later. If you have no further changes, just reply here so I can complete the merge.

l have no changes

2023-06-19 07:41 UTC, merged